import { Datetime } from '../../../../../eventEditor/data/types';
import { DatetimeStatus } from '../../../../../eventEditor/data/types';

const dates: Datetime[] = [
	{
		id: 'RGF0ZXRpbWU6ODM=',
		capacity: -1,
		isActive: true,
		sold: 0,
		dbId: 2,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isUpcoming: false,
		isDeleted: false,
		status: DatetimeStatus.active,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
	},
	{
		id: 'RGF0ZXRpbWU6ODM=',
		capacity: 10,
		isActive: true,
		sold: 5,
		status: DatetimeStatus.active,
		dbId: 3,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isUpcoming: false,
		isDeleted: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
	},
	{
		id: 'RGF0ZXRpbWU6ODM=',
		capacity: 10,
		isActive: true,
		sold: 6,
		status: DatetimeStatus.active,
		dbId: 4,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isUpcoming: false,
		isDeleted: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
	},
	{
		id: 'RGF0ZXRpbWU6ODM=',
		capacity: 10,
		isActive: true,
		sold: 7,
		status: DatetimeStatus.active,
		dbId: 5,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isUpcoming: false,
		isDeleted: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
	},
	{
		id: 'RGF0ZXRpbWU6ODM=',
		capacity: 10,
		isActive: true,
		sold: 8,
		status: DatetimeStatus.active,
		dbId: 6,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isUpcoming: false,
		isDeleted: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
	},
	{
		id: 'RGF0ZXRpbWU6ODM=',
		capacity: 10,
		isActive: false,
		isUpcoming: true,
		sold: 9,
		status: DatetimeStatus.active,
		dbId: 7,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isDeleted: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
	},
	{
		id: 'RGF0ZXRpbWU6ODM=',
		capacity: 10,
		isActive: false,
		isUpcoming: true,
		sold: 10,
		status: DatetimeStatus.active,
		dbId: 8,
		name: 'Hello',
		description: 'Test',
		endDate: 'some',
		isExpired: false,
		isPrimary: false,
		isSoldOut: false,
		isDeleted: false,
		length: null,
		order: 0,
		reserved: 0,
		startDate: 'end',
	},
];

export default dates;
