import { Ticket } from '../../../../eventEditor/data/types';

export const tickets: Ticket[] = [
	{
		id: '1',
		name: 'Free Ticket',
		description: 'description',
		startDate: '2019-11-27T21:43:26',
		endDate: '2019-12-27T23:59:00',
		min: 0,
		max: null,
		price: 0,
		sold: 0,
		quantity: 100,
		reserved: 0,
		uses: null,
		order: 0,
		dbId: 1,
		isDefault: false,
		isFree: false,
		isRequired: false,
		isSoldOut: false,
		isTaxable: false,
		isTrashed: false,
		reverseCalculate: true,
	},
	{
		id: '2',
		name: 'Free Ticket',
		description: 'description',
		startDate: '2019-11-27T21:43:26',
		endDate: '2019-12-27T23:59:00',
		min: 0,
		max: null,
		price: 0,
		sold: 0,
		quantity: 100,
		reserved: 0,
		uses: null,
		order: 0,
		dbId: 2,
		isDefault: false,
		isFree: false,
		isRequired: false,
		isSoldOut: false,
		isTaxable: false,
		isTrashed: false,
		reverseCalculate: true,
	},
	{
		id: '3',
		name: 'Free Ticket',
		description: 'description',
		startDate: '2019-11-27T21:43:26',
		endDate: '2019-12-27T23:59:00',
		min: 0,
		max: null,
		price: 0,
		sold: 0,
		quantity: 100,
		reserved: 0,
		uses: null,
		order: 0,
		dbId: 3,
		isDefault: false,
		isFree: false,
		isRequired: false,
		isSoldOut: false,
		isTaxable: false,
		isTrashed: false,
		reverseCalculate: true,
	},
	{
		id: '4',
		name: 'Free Ticket',
		description: 'description',
		startDate: '2019-11-27T21:43:26',
		endDate: '2019-12-27T23:59:00',
		min: 0,
		max: null,
		price: 0,
		sold: 0,
		quantity: 100,
		reserved: 0,
		uses: null,
		order: 0,
		dbId: 4,
		isDefault: false,
		isFree: false,
		isRequired: false,
		isSoldOut: false,
		isTaxable: false,
		isTrashed: false,
		reverseCalculate: true,
	},
	{
		id: '5',
		name: 'Free Ticket',
		description: 'description',
		startDate: '2019-11-27T21:43:26',
		endDate: '2019-12-27T23:59:00',
		min: 0,
		max: null,
		price: 0,
		sold: 0,
		quantity: 100,
		reserved: 0,
		uses: null,
		order: 0,
		dbId: 5,
		isDefault: false,
		isFree: false,
		isRequired: false,
		isSoldOut: false,
		isTaxable: false,
		isTrashed: false,
		reverseCalculate: true,
	},
];
