version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "15:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  reviewers:
  - tn3rb
  assignees:
  - tn3rb
  labels:
  - category:assets
  - "type:build-process \U0001F528"
  - status:review
  ignore:
  - dependency-name: "@wordpress/block-library"
    versions:
    - 2.28.6
    - 2.29.1
  - dependency-name: "@wordpress/a11y"
    versions:
    - 2.14.3
    - 2.15.0
  - dependency-name: "@wordpress/i18n"
    versions:
    - 3.18.0
  - dependency-name: core-js
    versions:
    - 3.9.1
  - dependency-name: "@wordpress/editor"
    versions:
    - 9.25.5
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "15:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  reviewers:
  - tn3rb
  assignees:
  - tn3rb
  labels:
  - category:assets
  - "type:build-process \U0001F528"
  - status:review
