# github label sync configuration file for EE repos
# install `https://github.com/Xiphe/github-sync-labels-milestones`
- repositories:
    - eventespresso/event-espresso-core
    - eventespresso/ee4-events-calendar
    - eventespresso/eea-authnet-accept
    - eventespresso/eea-stripe-gateway
    - eventespresso/eea-wait-lists
    - eventespresso/eea-barcode-scanner
    - eventespresso/eea-attendee-mover
    - eventespresso/eea-wpuser-integration
    - eventespresso/eea-mailchimp
    - eventespresso/eea-gutenberg
    - eventespresso/eea-people-addon
    - eventespresso/ee4-infusionsoft
    - eventespresso/ee4-promotions
    - eventespresso/eea-ticketing
    - eventespresso/eea-beaver-builder
    - eventespresso/eea-flexible-payment-method
    - eventespresso/ee4-mer
    - eventespresso/eea-affiliatewp
    - eventespresso/eea-payment-methods-pro
    - eventespresso/eea-automated-upcoming-event-notifications
    - eventespresso/eea-buddypress
    - eventespresso/eea-events-blog
    - eventespresso/eea-chase-orbital
    - eventespresso/eea-vanco-pm
    - eventespresso/eea-authnet-sim
    - eventespresso/eventsmart.com-website
    - eventespresso/eea-ipay88-gateway
    - eventespresso/eea-calendar-table-template
    - eventespresso/eea-category-accordian-template
    - eventespresso/eea-events-grid-view-template
    - eventespresso/eea-aim-echeck
    - eventespresso/eea-braintree-gateway
    - eventespresso/eea-evertec
    - eventespresso/eea-ideal-mollie-gateway
    - eventespresso/eea-migs-payment-method
    - eventespresso/eea-payflow-pro-gateway
    - eventespresso/eea-recurring-events-manager
    - eventespresso/eea-events-table-template
    - eventespresso/eea-social-buttons
    - eventespresso/eea-paygov-payment-method
    - eventespresso/eea-multisite
    - eventespresso/connect-oauth-middleman
    - eventespresso/eventespresso.com-website
    - eventespresso/eea-transfirst-gateway
    - eventespresso/eea-sage-pay-gateway
    - eventespresso/eea-quickbooks-gateway
    - eventespresso/eea-omise-payment-method
    - eventespresso/eea-firstdata-payeezy
    - eventespresso/eea-cybersource-gateway
    - eventespresso/eea-chase-orbital
    - eventespresso/eea-event-app-customization
    - eventespresso/grunt-wp-plugin-buildmachine
    - eventespresso/eea-paypal-smart-buttons
    - eventespresso/event-espresso-private
    - eventespresso/eea-attendee-importer
  milestones: []
  labels:
  # status labels
    - name: "status:needs-documentation"
      color: 3297c3
    - name: "status:backlog"
      color: 5c7145
    - name: "status:on-hold"
      color: 4f4a33
    - name: "status:waiting-refresh"
      color: 2460a7
    - name: "status:in-progress"
      color: 93b343
    - name: "status:next"
      color: 5c7145
    - name: "status:needs-testing"
      color: eb4f21
    - name: "status:merge"
      color: 66b3aa
    - name: "status:review"
      color: f7d500
    - name: "status:feedback-needed"
      color: a16ec6
    - name: "status:needs-more-info"
      color: e47e33
    - name: "status:add-sales-page"
      color: 9ddde4
    - name: "status: duplicate?"
      color: e5ff00
      previousNames:
        - status:duplicate
        - duplicate
    - name: "status:stale"
      color: a08e58
    - name: "status:unit-tests-required"
      color: 9ddde4
    - name: "status:triage"
      color: f06291
      previousNames:
        - "triage"
    - name: "status:please-fix"
      color: c52e75
    - name: "status:potential-duplicate"
      color: c2d800
      previousNames:
        - "potential-duplicate"
    # category labels
    - name: "category:security"
      color: abc2c1
    - name: "category:assets"
      color: abc2c1
      previousNames:
        - assets
    - name: "category:payment-methods"
      color: abc2c1
      previousNames:
        - "category:payment-methods-&-gateways"
    - name: "category:admin-pages"
      color: abc2c1
      previousNames:
        - "category:admin-pages-&-functionality"
    - name: "category:spco-&-registration"
      color: abc2c1
    - name: "category:core-plugin"
      color: abc2c1
    - name: "category:frontend-ui-&-ux"
      color: abc2c1
    - name: "category:admin-page-ui-&-ux"
      color: abc2c1
    - name: "category:messaging-&-messengers"
      color: abc2c1
    - name: "category:i18n"
      color: abc2c1
      previousNames:
        - i18n
    - name: "category:templates-shortcodes-and-widgets"
      color: abc2c1
    - name: "category:models-and-data-infrastructure"
      color: abc2c1
    - name: "category:general"
      color: abc2c1
    - name: "category:activation-installation-and-migration"
      color: abc2c1
    - name: "category:wp-multi-site"
      color: abc2c1
    - name: "category:3rd-party-integrations"
      color: abc2c1
    - name: "category:decision-analytics"
      color: abc2c1
    - name: "category:pue-uxip-and-licensing"
      color: abc2c1
    - name: "category:unit-tests"
      color: abc2c1
    - name: "category:forms-systems"
      color: abc2c1
    - name: "category:reports-exporting-importing"
      color: abc2c1
    - name: "category:user-management"
      color: abc2c1
    - name: "category:accessibility"
      color: abc2c1
    - name: "category:command-bus"
      color: abc2c1
      previousNames:
        - "category:command-bus-and-command-handlers"
    - name: "category:gutenberg"
      color: abc2c1
      previousNames:
        - gutenberg
    - name: "category:has-codebase-ticket"
      color: abc2c1
      previousNames:
        - has codebase ticket
    - name: "category:community-contribution"
      color: abc2c1
      previousNames:
        - community-contribution
    # priority labels
    - name: "priority:critical 🔥"
      color: b60205
      previousNames:
        - "priority:critical"
    - name: "priority:high"
      color: f7d500
    - name: "priority:normal"
      color: 93b343
    - name: "priority:low"
      color: 9ddde4
    # type labels
    - name: "type:support 🆘"
      color: efefef
      previousNames:
        - "type:support"
    - name: "type:bug 🐞"
      color: efefef
      previousNames:
        - bug
        - "type:bug"
        - "type:bug 🐛"
    - name: "type:build-process 🔨"
      color: efefef
      previousNames:
        - build-process
        - "type:build-process"
    - name: "type:code-quality 👾"
      color: efefef
    - name: "type:edge-case ⚠"
      color: efefef
    - name: "type:enhancement 🎉"
      color: efefef
      previousNames:
        - enhancement
        - "type:enhancement"
    - name: "type:task 🧹"
      color: efefef
      previousNames:
        - "type:task ✅"
        - "type:task"
    - name: "type:feature-request 🙏"
      color: efefef
      previousNames:
        - feature request
        - "type:feature-request"
    - name: "type:documentation 📖"
      color: efefef
      previousNames:
        - documentation
        - "type:documentation"
    - name: "type:design 📐"
      color: efefef
      previousNames:
        - "type:design"
    - name: "type:user-proofing 🛡"
      color: efefef
      previousNames:
        - "type:user-proofing"
    - name: "type:theme/plugin-conflict 💥"
      color: efefef
      previousNames:
        - "type:theme/plugin-conflict"
    - name: "type:question ❓"
      color: efefef
      previousNames:
        - question
        - "type:question"
    - name: "type:invalid 🦄"
      color: efefef
      previousNames:
        - invalid
        - "type:invalid"
        - "type-invalid 🦄"
    - name: "type:impacts-eventsmart 🎫"
      color: 00f2ff
      previousNames:
        - "type:impacts-eventsmart"
    - name: "requires:WP5.0+ 🧩"
      color: 2a1f78
    ## depends-on-labels
    - name: "requires:WP5.0 🧩"
      color: 2a1f78
      previousNames:
        - requires:WP5.0+ 🧩
    - name: "requires:WP5.2 🧩"
      color: 2a1f78
    - name: "EZ"
      color: 91ff50
  options:
    ignoreMilestones:
      - eventespresso/event-espresso-core
      - eventespresso/ee4-events-calendar
      - eventespresso/eea-authnet-accept
      - eventespresso/eea-stripe-gateway
      - eventespresso/eea-wait-lists
      - eventespresso/eea-barcode-scanner
      - eventespresso/eea-attendee-mover
      - eventespresso/eea-wpuser-integration
      - eventespresso/eea-mailchimp
      - eventespresso/eea-gutenberg
      - eventespresso/eea-people-addon
      - eventespresso/ee4-infusionsoft
      - eventespresso/ee4-promotions
      - eventespresso/eea-ticketing
      - eventespresso/eea-beaver-builder
      - eventespresso/eea-flexible-payment-method
      - eventespresso/ee4-mer
      - eventespresso/eea-affiliatewp
      - eventespresso/eea-payment-methods-pro
      - eventespresso/eea-automated-upcoming-event-notifications
      - eventespresso/eea-buddypress
      - eventespresso/eea-events-blog
      - eventespresso/eea-chase-orbital
      - eventespresso/eea-vanco-pm
      - eventespresso/eea-authnet-sim
      - eventespresso/eventsmart.com-website
      - eventespresso/eea-ipay88-gateway
      - eventespresso/eea-calendar-table-template
      - eventespresso/eea-category-accordian-template
      - eventespresso/eea-events-grid-view-template
      - eventespresso/eea-aim-echeck
      - eventespresso/eea-braintree-gateway
      - eventespresso/eea-evertec
      - eventespresso/eea-ideal-mollie-gateway
      - eventespresso/eea-migs-payment-method
      - eventespresso/eea-payflow-pro-gateway
      - eventespresso/eea-recurring-events-manager
      - eventespresso/eea-events-table-template
      - eventespresso/eea-social-buttons
      - eventespresso/eea-paygov-payment-method
      - eventespresso/eea-multisite
      - eventespresso/connect-oauth-middleman
      - eventespresso/eventespresso.com-website
      - eventespresso/eea-transfirst-gateway
      - eventespresso/eea-sage-pay-gateway
      - eventespresso/eea-quickbooks-gateway
      - eventespresso/eea-omise-payment-method
      - eventespresso/eea-firstdata-payeezy
      - eventespresso/eea-cybersource-gateway
      - eventespresso/eea-chase-orbital
      - eventespresso/eea-event-app-customization
      - eventespresso/grunt-wp-plugin-buildmachine