"<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: price in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php on line <i>111</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>145232</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.7161</td><td bgcolor='#eeeeec' align='right'>20181888</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182856</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182872</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout::process_reg_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>2.7309</td><td bgcolor='#eeeeec' align='right'>20661832</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>110</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.0099</td><td bgcolor='#eeeeec' align='right'>21228928</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>1111</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.0100</td><td bgcolor='#eeeeec' align='right'>21229992</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>3.0100</td><td bgcolor='#eeeeec' align='right'>21230008</td><td bgcolor='#eeeeec'>EE_messages_init->registration(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>3.1501</td><td bgcolor='#eeeeec' align='right'>22056344</td><td bgcolor='#eeeeec'>EE_messages->send_message(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages_init.core.php' bgcolor='#eeeeec'>..\EE_messages_init.core.php<b>:</b>186</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>3.1501</td><td bgcolor='#eeeeec' align='right'>22056528</td><td bgcolor='#eeeeec'>EE_message_type->set_messages(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages.core.php' bgcolor='#eeeeec'>..\EE_messages.core.php<b>:</b>160</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>3.1508</td><td bgcolor='#eeeeec' align='right'>22078120</td><td bgcolor='#eeeeec'>EE_message_type->_init_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>201</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22115632</td><td bgcolor='#eeeeec'>ReflectionClass->newInstance(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116296</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116296</td><td bgcolor='#eeeeec'>EE_Messages_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php' bgcolor='#eeeeec'>..\EE_Messages_EE_Session_incoming_data.class.php<b>:</b>35</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116288</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->_setup_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_incoming_data.core.php' bgcolor='#eeeeec'>..\EE_Messages_incoming_data.core.php<b>:</b>163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: price_obj in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php on line <i>112</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>145232</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.7161</td><td bgcolor='#eeeeec' align='right'>20181888</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182856</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182872</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout::process_reg_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>2.7309</td><td bgcolor='#eeeeec' align='right'>20661832</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>110</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.0099</td><td bgcolor='#eeeeec' align='right'>21228928</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>1111</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.0100</td><td bgcolor='#eeeeec' align='right'>21229992</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>3.0100</td><td bgcolor='#eeeeec' align='right'>21230008</td><td bgcolor='#eeeeec'>EE_messages_init->registration(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>3.1501</td><td bgcolor='#eeeeec' align='right'>22056344</td><td bgcolor='#eeeeec'>EE_messages->send_message(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages_init.core.php' bgcolor='#eeeeec'>..\EE_messages_init.core.php<b>:</b>186</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>3.1501</td><td bgcolor='#eeeeec' align='right'>22056528</td><td bgcolor='#eeeeec'>EE_message_type->set_messages(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages.core.php' bgcolor='#eeeeec'>..\EE_messages.core.php<b>:</b>160</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>3.1508</td><td bgcolor='#eeeeec' align='right'>22078120</td><td bgcolor='#eeeeec'>EE_message_type->_init_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>201</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22115632</td><td bgcolor='#eeeeec'>ReflectionClass->newInstance(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116296</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116296</td><td bgcolor='#eeeeec'>EE_Messages_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php' bgcolor='#eeeeec'>..\EE_Messages_EE_Session_incoming_data.class.php<b>:</b>35</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116288</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->_setup_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_incoming_data.core.php' bgcolor='#eeeeec'>..\EE_Messages_incoming_data.core.php<b>:</b>163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: price_desc in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php on line <i>113</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>145232</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.7161</td><td bgcolor='#eeeeec' align='right'>20181888</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182856</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182872</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout::process_reg_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>2.7309</td><td bgcolor='#eeeeec' align='right'>20661832</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>110</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.0099</td><td bgcolor='#eeeeec' align='right'>21228928</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>1111</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.0100</td><td bgcolor='#eeeeec' align='right'>21229992</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>3.0100</td><td bgcolor='#eeeeec' align='right'>21230008</td><td bgcolor='#eeeeec'>EE_messages_init->registration(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>3.1501</td><td bgcolor='#eeeeec' align='right'>22056344</td><td bgcolor='#eeeeec'>EE_messages->send_message(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages_init.core.php' bgcolor='#eeeeec'>..\EE_messages_init.core.php<b>:</b>186</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>3.1501</td><td bgcolor='#eeeeec' align='right'>22056528</td><td bgcolor='#eeeeec'>EE_message_type->set_messages(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages.core.php' bgcolor='#eeeeec'>..\EE_messages.core.php<b>:</b>160</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>3.1508</td><td bgcolor='#eeeeec' align='right'>22078120</td><td bgcolor='#eeeeec'>EE_message_type->_init_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>201</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22115632</td><td bgcolor='#eeeeec'>ReflectionClass->newInstance(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116296</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116296</td><td bgcolor='#eeeeec'>EE_Messages_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php' bgcolor='#eeeeec'>..\EE_Messages_EE_Session_incoming_data.class.php<b>:</b>35</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116288</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->_setup_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_incoming_data.core.php' bgcolor='#eeeeec'>..\EE_Messages_incoming_data.core.php<b>:</b>163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: price_id in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php on line <i>115</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>145232</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.7161</td><td bgcolor='#eeeeec' align='right'>20181888</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182856</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182872</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout::process_reg_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>2.7309</td><td bgcolor='#eeeeec' align='right'>20661832</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>110</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.0099</td><td bgcolor='#eeeeec' align='right'>21228928</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>1111</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.0100</td><td bgcolor='#eeeeec' align='right'>21229992</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>3.0100</td><td bgcolor='#eeeeec' align='right'>21230008</td><td bgcolor='#eeeeec'>EE_messages_init->registration(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>3.1501</td><td bgcolor='#eeeeec' align='right'>22056344</td><td bgcolor='#eeeeec'>EE_messages->send_message(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages_init.core.php' bgcolor='#eeeeec'>..\EE_messages_init.core.php<b>:</b>186</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>3.1501</td><td bgcolor='#eeeeec' align='right'>22056528</td><td bgcolor='#eeeeec'>EE_message_type->set_messages(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages.core.php' bgcolor='#eeeeec'>..\EE_messages.core.php<b>:</b>160</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>3.1508</td><td bgcolor='#eeeeec' align='right'>22078120</td><td bgcolor='#eeeeec'>EE_message_type->_init_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>201</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22115632</td><td bgcolor='#eeeeec'>ReflectionClass->newInstance(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116296</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116296</td><td bgcolor='#eeeeec'>EE_Messages_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php' bgcolor='#eeeeec'>..\EE_Messages_EE_Session_incoming_data.class.php<b>:</b>35</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116288</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->_setup_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_incoming_data.core.php' bgcolor='#eeeeec'>..\EE_Messages_incoming_data.core.php<b>:</b>163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: event_meta in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php on line <i>116</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>145232</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.7161</td><td bgcolor='#eeeeec' align='right'>20181888</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182856</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182872</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout::process_reg_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>2.7309</td><td bgcolor='#eeeeec' align='right'>20661832</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>110</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.0099</td><td bgcolor='#eeeeec' align='right'>21228928</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>1111</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.0100</td><td bgcolor='#eeeeec' align='right'>21229992</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>3.0100</td><td bgcolor='#eeeeec' align='right'>21230008</td><td bgcolor='#eeeeec'>EE_messages_init->registration(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>3.1501</td><td bgcolor='#eeeeec' align='right'>22056344</td><td bgcolor='#eeeeec'>EE_messages->send_message(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages_init.core.php' bgcolor='#eeeeec'>..\EE_messages_init.core.php<b>:</b>186</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>3.1501</td><td bgcolor='#eeeeec' align='right'>22056528</td><td bgcolor='#eeeeec'>EE_message_type->set_messages(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages.core.php' bgcolor='#eeeeec'>..\EE_messages.core.php<b>:</b>160</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>3.1508</td><td bgcolor='#eeeeec' align='right'>22078120</td><td bgcolor='#eeeeec'>EE_message_type->_init_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>201</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22115632</td><td bgcolor='#eeeeec'>ReflectionClass->newInstance(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116296</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116296</td><td bgcolor='#eeeeec'>EE_Messages_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php' bgcolor='#eeeeec'>..\EE_Messages_EE_Session_incoming_data.class.php<b>:</b>35</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>3.1558</td><td bgcolor='#eeeeec' align='right'>22116288</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->_setup_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_incoming_data.core.php' bgcolor='#eeeeec'>..\EE_Messages_incoming_data.core.php<b>:</b>163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: price in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php on line <i>111</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>145232</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.7161</td><td bgcolor='#eeeeec' align='right'>20181888</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182856</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182872</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout::process_reg_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>2.7309</td><td bgcolor='#eeeeec' align='right'>20661832</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>110</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.0099</td><td bgcolor='#eeeeec' align='right'>21228928</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>1111</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.4991</td><td bgcolor='#eeeeec' align='right'>22856120</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>3.4991</td><td bgcolor='#eeeeec' align='right'>22856136</td><td bgcolor='#eeeeec'>EE_messages_init->registration(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>3.6124</td><td bgcolor='#eeeeec' align='right'>23253056</td><td bgcolor='#eeeeec'>EE_messages->send_message(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages_init.core.php' bgcolor='#eeeeec'>..\EE_messages_init.core.php<b>:</b>186</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>3.6124</td><td bgcolor='#eeeeec' align='right'>23253120</td><td bgcolor='#eeeeec'>EE_message_type->set_messages(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages.core.php' bgcolor='#eeeeec'>..\EE_messages.core.php<b>:</b>160</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23253504</td><td bgcolor='#eeeeec'>EE_message_type->_init_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>201</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23253792</td><td bgcolor='#eeeeec'>ReflectionClass->newInstance(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254456</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254456</td><td bgcolor='#eeeeec'>EE_Messages_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php' bgcolor='#eeeeec'>..\EE_Messages_EE_Session_incoming_data.class.php<b>:</b>35</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254424</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->_setup_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_incoming_data.core.php' bgcolor='#eeeeec'>..\EE_Messages_incoming_data.core.php<b>:</b>163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: price_obj in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php on line <i>112</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>145232</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.7161</td><td bgcolor='#eeeeec' align='right'>20181888</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182856</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182872</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout::process_reg_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>2.7309</td><td bgcolor='#eeeeec' align='right'>20661832</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>110</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.0099</td><td bgcolor='#eeeeec' align='right'>21228928</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>1111</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.4991</td><td bgcolor='#eeeeec' align='right'>22856120</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>3.4991</td><td bgcolor='#eeeeec' align='right'>22856136</td><td bgcolor='#eeeeec'>EE_messages_init->registration(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>3.6124</td><td bgcolor='#eeeeec' align='right'>23253056</td><td bgcolor='#eeeeec'>EE_messages->send_message(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages_init.core.php' bgcolor='#eeeeec'>..\EE_messages_init.core.php<b>:</b>186</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>3.6124</td><td bgcolor='#eeeeec' align='right'>23253120</td><td bgcolor='#eeeeec'>EE_message_type->set_messages(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages.core.php' bgcolor='#eeeeec'>..\EE_messages.core.php<b>:</b>160</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23253504</td><td bgcolor='#eeeeec'>EE_message_type->_init_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>201</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23253792</td><td bgcolor='#eeeeec'>ReflectionClass->newInstance(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254456</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254456</td><td bgcolor='#eeeeec'>EE_Messages_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php' bgcolor='#eeeeec'>..\EE_Messages_EE_Session_incoming_data.class.php<b>:</b>35</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254424</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->_setup_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_incoming_data.core.php' bgcolor='#eeeeec'>..\EE_Messages_incoming_data.core.php<b>:</b>163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: price_desc in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php on line <i>113</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>145232</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.7161</td><td bgcolor='#eeeeec' align='right'>20181888</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182856</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182872</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout::process_reg_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>2.7309</td><td bgcolor='#eeeeec' align='right'>20661832</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>110</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.0099</td><td bgcolor='#eeeeec' align='right'>21228928</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>1111</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.4991</td><td bgcolor='#eeeeec' align='right'>22856120</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>3.4991</td><td bgcolor='#eeeeec' align='right'>22856136</td><td bgcolor='#eeeeec'>EE_messages_init->registration(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>3.6124</td><td bgcolor='#eeeeec' align='right'>23253056</td><td bgcolor='#eeeeec'>EE_messages->send_message(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages_init.core.php' bgcolor='#eeeeec'>..\EE_messages_init.core.php<b>:</b>186</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>3.6124</td><td bgcolor='#eeeeec' align='right'>23253120</td><td bgcolor='#eeeeec'>EE_message_type->set_messages(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages.core.php' bgcolor='#eeeeec'>..\EE_messages.core.php<b>:</b>160</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23253504</td><td bgcolor='#eeeeec'>EE_message_type->_init_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>201</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23253792</td><td bgcolor='#eeeeec'>ReflectionClass->newInstance(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254456</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254456</td><td bgcolor='#eeeeec'>EE_Messages_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php' bgcolor='#eeeeec'>..\EE_Messages_EE_Session_incoming_data.class.php<b>:</b>35</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254424</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->_setup_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_incoming_data.core.php' bgcolor='#eeeeec'>..\EE_Messages_incoming_data.core.php<b>:</b>163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: price_id in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php on line <i>115</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>145232</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.7161</td><td bgcolor='#eeeeec' align='right'>20181888</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182856</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182872</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout::process_reg_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>2.7309</td><td bgcolor='#eeeeec' align='right'>20661832</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>110</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.0099</td><td bgcolor='#eeeeec' align='right'>21228928</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>1111</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.4991</td><td bgcolor='#eeeeec' align='right'>22856120</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>3.4991</td><td bgcolor='#eeeeec' align='right'>22856136</td><td bgcolor='#eeeeec'>EE_messages_init->registration(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>3.6124</td><td bgcolor='#eeeeec' align='right'>23253056</td><td bgcolor='#eeeeec'>EE_messages->send_message(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages_init.core.php' bgcolor='#eeeeec'>..\EE_messages_init.core.php<b>:</b>186</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>3.6124</td><td bgcolor='#eeeeec' align='right'>23253120</td><td bgcolor='#eeeeec'>EE_message_type->set_messages(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages.core.php' bgcolor='#eeeeec'>..\EE_messages.core.php<b>:</b>160</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23253504</td><td bgcolor='#eeeeec'>EE_message_type->_init_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>201</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23253792</td><td bgcolor='#eeeeec'>ReflectionClass->newInstance(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254456</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254456</td><td bgcolor='#eeeeec'>EE_Messages_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php' bgcolor='#eeeeec'>..\EE_Messages_EE_Session_incoming_data.class.php<b>:</b>35</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254424</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->_setup_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_incoming_data.core.php' bgcolor='#eeeeec'>..\EE_Messages_incoming_data.core.php<b>:</b>163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: event_meta in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php on line <i>116</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>145232</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>2.7161</td><td bgcolor='#eeeeec' align='right'>20181888</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182856</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>2.7162</td><td bgcolor='#eeeeec' align='right'>20182872</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout::process_reg_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>2.7309</td><td bgcolor='#eeeeec' align='right'>20661832</td><td bgcolor='#eeeeec'>EED_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>110</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>3.0099</td><td bgcolor='#eeeeec' align='right'>21228928</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\modules\single_page_checkout\EED_Single_Page_Checkout.module.php' bgcolor='#eeeeec'>..\EED_Single_Page_Checkout.module.php<b>:</b>1111</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>3.4991</td><td bgcolor='#eeeeec' align='right'>22856120</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>3.4991</td><td bgcolor='#eeeeec' align='right'>22856136</td><td bgcolor='#eeeeec'>EE_messages_init->registration(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>3.6124</td><td bgcolor='#eeeeec' align='right'>23253056</td><td bgcolor='#eeeeec'>EE_messages->send_message(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages_init.core.php' bgcolor='#eeeeec'>..\EE_messages_init.core.php<b>:</b>186</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>3.6124</td><td bgcolor='#eeeeec' align='right'>23253120</td><td bgcolor='#eeeeec'>EE_message_type->set_messages(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_messages.core.php' bgcolor='#eeeeec'>..\EE_messages.core.php<b>:</b>160</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23253504</td><td bgcolor='#eeeeec'>EE_message_type->_init_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>201</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23253792</td><td bgcolor='#eeeeec'>ReflectionClass->newInstance(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254456</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\EE_message_type.core.php' bgcolor='#eeeeec'>..\EE_message_type.core.php<b>:</b>330</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254456</td><td bgcolor='#eeeeec'>EE_Messages_incoming_data->__construct(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_EE_Session_incoming_data.class.php' bgcolor='#eeeeec'>..\EE_Messages_EE_Session_incoming_data.class.php<b>:</b>35</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>3.6126</td><td bgcolor='#eeeeec' align='right'>23254424</td><td bgcolor='#eeeeec'>EE_Messages_EE_Session_incoming_data->_setup_data(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\core\messages\data_class\EE_Messages_incoming_data.core.php' bgcolor='#eeeeec'>..\EE_Messages_incoming_data.core.php<b>:</b>163</td></tr>
</table></font>
{"success":true,"return_data":{"redirect-to-thank-you-page":"http:\/\/localhost\/Wordpress2\/thank-you?e_reg_url_link=cc5bf5e4c3f421084dcb621700567a61"}}"