module.exports = {
	roots: ['<rootDir>/assets/src'],
	testMatch: ['<rootDir>/assets/src/**/*.test.{ts,tsx}'],
	transform: {
		'^.+\\.(js|jsx)$': '<rootDir>/node_modules/babel-jest',
		'^.+\\.(ts|tsx)$': '<rootDir>/node_modules/ts-jest',
		'^.+\\.css$': '<rootDir>/config/jest/cssTransform.js',
		'^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '<rootDir>/config/jest/fileTransform.js',
	},
	collectCoverageFrom: ['assets/src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts'],
	setupFiles: ['react-app-polyfill/jsdom'],
	setupFilesAfterEnv: ['<rootDir>/config/jest/setupTests.ts'],
	testEnvironment: 'jest-environment-jsdom-fourteen',
	transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$', '^.+\\.module\\.(css|sass|scss)$'],
	modulePaths: [],
	moduleNameMapper: {
		'^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
		'@application/(.*)': '<rootDir>/assets/src/application/$1',
		'@appConstants/(.*)': '<rootDir>/assets/src/application/constants/$1',
		'@appServices/(.*)': '<rootDir>/assets/src/application/services/$1',
		'@appCalendars/(.*)': '<rootDir>/assets/src/application/ui/calendars/$1',
		'@appDisplay/(.*)': '<rootDir>/assets/src/application/ui/display/$1',
		'@appForms/(.*)': '<rootDir>/assets/src/application/ui/forms/$1',
		'@appInputs/(.*)': '<rootDir>/assets/src/application/ui/input/$1',
		'@appLayout/(.*)': '<rootDir>/assets/src/application/ui/layout/$1',
		'@appConfig/(.*)': '<rootDir>/assets/src/application/valueObjects/config/$1',
		'@edtrHooks/(.*)': '<rootDir>/assets/src/domain/eventEditor/hooks/$1',
		'@edtrInterfaces/(.*)': '<rootDir>/assets/src/domain/eventEditor/interfaces/$1',
		'@edtrServices/(.*)': '<rootDir>/assets/src/domain/eventEditor/services/$1',
		'@edtrUI/(.*)': '<rootDir>/assets/src/domain/eventEditor/ui/$1',
		'@sharedConstants/(.*)': '<rootDir>/assets/src/domain/shared/constants/$1',
		'@sharedServices/(.*)': '<rootDir>/assets/src/domain/shared/services/$1',
		'@sharedEntities/(.*)': '<rootDir>/assets/src/domain/shared/entities/$1',
		'@sharedUI/(.*)': '<rootDir>/assets/src/domain/shared/ui/$1',
		'@infraServices/(.*)': '<rootDir>/assets/src/infrastructure/services/$1',
		'@infraUI/(.*)': '<rootDir>/assets/src/infrastructure/ui/$1',
	},
	moduleFileExtensions: ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'],
	watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
};
