"<br />
<font size='1'><table class='xdebug-error xe-warning xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Missing argument 1 for current_time(), called in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php on line 1163 and defined in C:\xampp\htdocs\Wordpress2\wp-includes\functions.php on line <i>59</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0013</td><td bgcolor='#eeeeec' align='right'>145168</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>1.3513</td><td bgcolor='#eeeeec' align='right'>15903672</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904648</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904696</td><td bgcolor='#eeeeec'>EE_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>1.3515</td><td bgcolor='#eeeeec' align='right'>15905288</td><td bgcolor='#eeeeec'>current_time(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php' bgcolor='#eeeeec'>..\EE_Single_Page_Checkout.class.php<b>:</b>1163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: type in C:\xampp\htdocs\Wordpress2\wp-includes\functions.php on line <i>61</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0013</td><td bgcolor='#eeeeec' align='right'>145168</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>1.3513</td><td bgcolor='#eeeeec' align='right'>15903672</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904648</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904696</td><td bgcolor='#eeeeec'>EE_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>1.3515</td><td bgcolor='#eeeeec' align='right'>15905288</td><td bgcolor='#eeeeec'>current_time(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php' bgcolor='#eeeeec'>..\EE_Single_Page_Checkout.class.php<b>:</b>1163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: type in C:\xampp\htdocs\Wordpress2\wp-includes\functions.php on line <i>64</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0013</td><td bgcolor='#eeeeec' align='right'>145168</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>1.3513</td><td bgcolor='#eeeeec' align='right'>15903672</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904648</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904696</td><td bgcolor='#eeeeec'>EE_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>1.3515</td><td bgcolor='#eeeeec' align='right'>15905288</td><td bgcolor='#eeeeec'>current_time(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php' bgcolor='#eeeeec'>..\EE_Single_Page_Checkout.class.php<b>:</b>1163</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Missing argument 1 for current_time(), called in C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php on line 1317 and defined in C:\xampp\htdocs\Wordpress2\wp-includes\functions.php on line <i>59</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0013</td><td bgcolor='#eeeeec' align='right'>145168</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>1.3513</td><td bgcolor='#eeeeec' align='right'>15903672</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904648</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904696</td><td bgcolor='#eeeeec'>EE_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>1.3593</td><td bgcolor='#eeeeec' align='right'>15958240</td><td bgcolor='#eeeeec'>EE_Single_Page_Checkout::save_registration_items(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php' bgcolor='#eeeeec'>..\EE_Single_Page_Checkout.class.php<b>:</b>1179</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>1.3656</td><td bgcolor='#eeeeec' align='right'>16101408</td><td bgcolor='#eeeeec'>current_time(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php' bgcolor='#eeeeec'>..\EE_Single_Page_Checkout.class.php<b>:</b>1317</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: type in C:\xampp\htdocs\Wordpress2\wp-includes\functions.php on line <i>61</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0013</td><td bgcolor='#eeeeec' align='right'>145168</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>1.3513</td><td bgcolor='#eeeeec' align='right'>15903672</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904648</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904696</td><td bgcolor='#eeeeec'>EE_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>1.3593</td><td bgcolor='#eeeeec' align='right'>15958240</td><td bgcolor='#eeeeec'>EE_Single_Page_Checkout::save_registration_items(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php' bgcolor='#eeeeec'>..\EE_Single_Page_Checkout.class.php<b>:</b>1179</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>1.3656</td><td bgcolor='#eeeeec' align='right'>16101408</td><td bgcolor='#eeeeec'>current_time(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php' bgcolor='#eeeeec'>..\EE_Single_Page_Checkout.class.php<b>:</b>1317</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice xe-scream' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> SCREAM: Error suppression ignored for</th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: type in C:\xampp\htdocs\Wordpress2\wp-includes\functions.php on line <i>64</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0013</td><td bgcolor='#eeeeec' align='right'>145168</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>1.3513</td><td bgcolor='#eeeeec' align='right'>15903672</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904648</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>1.3514</td><td bgcolor='#eeeeec' align='right'>15904696</td><td bgcolor='#eeeeec'>EE_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>1.3593</td><td bgcolor='#eeeeec' align='right'>15958240</td><td bgcolor='#eeeeec'>EE_Single_Page_Checkout::save_registration_items(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php' bgcolor='#eeeeec'>..\EE_Single_Page_Checkout.class.php<b>:</b>1179</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>1.3656</td><td bgcolor='#eeeeec' align='right'>16101408</td><td bgcolor='#eeeeec'>current_time(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php' bgcolor='#eeeeec'>..\EE_Single_Page_Checkout.class.php<b>:</b>1317</td></tr>
</table></font>
{"success":true,"return_data":{"redirect-to-thank-you-page":"http:\/\/localhost\/Wordpress2\/?page_id=5&e_reg_url_link=4c142b45dc66938e8e6a711b501593e2"}}"