<?php

namespace EventEspresso\caffeinated\payment_methods\Paypal_Smart_Buttons\forms;

use EE_Hidden_Input;
use EE_Payment_Method_Form;
use EE_Select_Input;
use EE_Text_Input;
use WP_Error;

/**
 * Class PayPalSmartButtonSettingsForm
 *
 * Form for the PayPal Smart Buttons payment method. One special bit of functionality: it validates
 * the user's client ID and secret, and if they work, stores the authorization token which will be used
 * for REST API requests.
 * See https://developer.paypal.com/docs/api/overview/#get-an-access-token for how we do this.
 *
 * @package        Event Espresso
 * @author         Mike Nelson
 * @since          $VID:$
 *
 */
class PayPalSmartButtonSettingsForm extends EE_Payment_Method_Form
{

    public function __construct($help_tab_link, array $options_array = array())
    {
        $options_array = array_merge_recursive(
            $options_array,
            array(
                'extra_meta_inputs' => array(
                    'client_id'    => new EE_Text_Input(
                        array(
                            'html_label_text' => sprintf(
                                _x(
                                    'PayPal REST API App Client ID %s',
                                    'PayPal REST API App Client ID (help link)',
                                    'event_espresso'
                                ),
                                $help_tab_link
                            ),
                            'required'        => true,
                        )
                    ),
                    'secret'       => new EE_Text_Input(
                        array(
                            'html_label_text' => sprintf(
                                _x(
                                    'PayPal REST API App Secret %s',
                                    'PayPal REST API App Secret (help link)',
                                    'event_espresso'
                                ),
                                $help_tab_link
                            ),
                            'required'        => true,
                        )
                    ),
                    'button_color' => new EE_Select_Input(
                        array(
                            ''         => esc_html__('Default', 'event_espresso'),
                            'gold'     => esc_html__('Gold', 'event_espresso'),
                            'blue'     => esc_html__('Blue', 'event_espresso'),
                            'darkblue' => esc_html__('Dark Blue', 'event_espresso'),
                            'silver'   => esc_html__('Silver', 'event_espresso'),
                            'black'    => esc_html__('Black', 'event_espresso'),
                        ),
                        array(
                            'html_label_text' => esc_html__('Button Color', 'event_espresso'),
                            'default'         => '',
                        )
                    ),
                    'button_shape' => new EE_Select_Input(
                        array(
                            'pill' => esc_html__('Pill (Recommended)', 'event_espresso'),
                            'rect' => esc_html__('Rectangular', 'event_espresso'),
                        ),
                        array(
                            'html_label_text' => esc_html__('Button Shape', 'event_espresso'),
                            'default'         => 'pill',
                        )
                    ),
                    'button_size'  => new EE_Select_Input(
                        array(
                            'medium'     => esc_html__('Medium (250px by 35px)', 'event_espresso'),
                            'large'      => esc_html__('Large (350px by 40px)', 'event_espresso'),
                            'responsive' => esc_html__('Responsive (fills the page)', 'event_espresso'),
                        ),
                        array(
                            'html_label_text' => esc_html__('Button Size', 'event_espresso'),
                            'default'         => 'medium',
                        )
                    ),
                    // store the access token like other extra meta inputs
                    // except hide it, because we don't ask users for it directly. We will retrieve it from
                    // PayPal upon form submission
                    'access_token' => new EE_Hidden_Input()
                ),
                'exclude'           => array(
                    'PMD_button_url',
                ),
            )
        );
        parent::__construct($options_array);
    }


    /**
     * @return bool|void
     * @throws \EE_Error
     */
    public function _validate()
    {
        parent::_validate(); // TODO: Change the autogenerated stub
        //also, let's check the credentials are valid.
        $valid_data = $this->valid_data();
        if (isset($valid_data['client_id'], $valid_data['secret'])) {
            $response = wp_remote_post(
                'https://api.sandbox.paypal.com/v1/oauth2/token',
                array(
                    'headers' => array(
                        'Accept'        => 'application/json',
                        'Authorization' => 'Basic ' . base64_encode($valid_data['client_id'] . ':' . $valid_data['secret']),
                    ),
                    'body'    => array(
                        'grant_type' => 'client_credentials',
                    ),
                )
            );
            if (is_wp_error($response)) {
                /**
                 * @var $response WP_Error
                 */
                $this->add_validation_error(
                    esc_html(
                        sprintf(
                            _x(
                                'There was an error while validating your PayPal credentials. The error was: %1$s',
                                'There was an error while validating your PayPal credentials. The error was: (error message)',
                                'event_espresso'
                            ),
                            $response->get_error_message()
                        )
                    )
                );
            }
            $response_body = wp_remote_retrieve_body($response);
            if( ! $response_body) {
                $this->add_validation_error(
                    esc_html__(
                            'There was an error while validating your PayPal credentials. No response was received from PayPal',
                            'event_espresso'
                    )
                );
            }
            $response_json = json_decode($response_body, true);
            if (! is_array($response_json)) {
                $this->add_validation_error(
                    esc_html__('There was an error while validating your PayPal Credentials. No JSON body was received.', 'event_espresso')
                );
            }
            if( isset($response_json['error'], $response_json['error_description'])) {
                $this->add_validation_error(
                    esc_html(
                        sprintf(
                            _x(
                                'There was an error validating your PayPal credentials. %1$s (%2$s)',
                                'There was an error validating your PayPal credentials. Error message (error_code)',
                                'event_espresso'
                            ),
                            $response_json['error_description'],
                            $response_json['error']
                        )
                    )
                );
            }
        }
        if (isset($response_json['access_token'])) {
            $this->populate_defaults(
                array(
                    'access_token' => $response_json['access_token']
                )
            );
        }
    }
}
// End of file PayPalSmartButtonSettingsForm.php
// Location: EventEspresso\caffeinated\payment_methods\Paypal_Smart_Buttons\forms/PayPalSmartButtonSettingsForm.php
