"<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: mysql_real_escape_string() expects parameter 1 to be string, array given in C:\xampp\htdocs\Wordpress2\wp-includes\wp-db.php on line <i>885</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0017</td><td bgcolor='#eeeeec' align='right'>144256</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>1.3751</td><td bgcolor='#eeeeec' align='right'>15260184</td><td bgcolor='#eeeeec'>do_action(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-admin\admin-ajax.php' bgcolor='#eeeeec'>..\admin-ajax.php<b>:</b>72</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>1.3751</td><td bgcolor='#eeeeec' align='right'>15261160</td><td bgcolor='#eeeeec'><a href='http://www.php.net/call_user_func_array' target='_new'>call_user_func_array</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>1.3751</td><td bgcolor='#eeeeec' align='right'>15261208</td><td bgcolor='#eeeeec'>EE_Single_Page_Checkout->process_registration_step_3(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\plugin.php' bgcolor='#eeeeec'>..\plugin.php<b>:</b>406</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>1.3784</td><td bgcolor='#eeeeec' align='right'>15464048</td><td bgcolor='#eeeeec'>EE_Base_Class->save(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Single_Page_Checkout.class.php' bgcolor='#eeeeec'>..\EE_Single_Page_Checkout.class.php<b>:</b>1154</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>1.3785</td><td bgcolor='#eeeeec' align='right'>15465200</td><td bgcolor='#eeeeec'>EEM_Transaction->insert(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\classes\EE_Base_Class.class.php' bgcolor='#eeeeec'>..\EE_Base_Class.class.php<b>:</b>418</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>1.3785</td><td bgcolor='#eeeeec' align='right'>15465232</td><td bgcolor='#eeeeec'>EEM_Base->_insert(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\models\EEM_Transaction.model.php' bgcolor='#eeeeec'>..\EEM_Transaction.model.php<b>:</b>461</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>1.3786</td><td bgcolor='#eeeeec' align='right'>15466576</td><td bgcolor='#eeeeec'>wpdb->insert(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-content\plugins\32-core\includes\models\EEM_Base.model.php' bgcolor='#eeeeec'>..\EEM_Base.model.php<b>:</b>623</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>1.3786</td><td bgcolor='#eeeeec' align='right'>15466640</td><td bgcolor='#eeeeec'>wpdb->_insert_replace_helper(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\wp-db.php' bgcolor='#eeeeec'>..\wp-db.php<b>:</b>1256</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>1.3786</td><td bgcolor='#eeeeec' align='right'>15469392</td><td bgcolor='#eeeeec'>wpdb->prepare(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\wp-db.php' bgcolor='#eeeeec'>..\wp-db.php<b>:</b>1316</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>1.3786</td><td bgcolor='#eeeeec' align='right'>15470696</td><td bgcolor='#eeeeec'><a href='http://www.php.net/array_walk' target='_new'>array_walk</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\wp-db.php' bgcolor='#eeeeec'>..\wp-db.php<b>:</b>1006</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>1.3787</td><td bgcolor='#eeeeec' align='right'>15472384</td><td bgcolor='#eeeeec'>wpdb->escape_by_ref(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\wp-db.php' bgcolor='#eeeeec'>..\wp-db.php<b>:</b>1006</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>1.3787</td><td bgcolor='#eeeeec' align='right'>15473744</td><td bgcolor='#eeeeec'>wpdb->_real_escape(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\wp-db.php' bgcolor='#eeeeec'>..\wp-db.php<b>:</b>950</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>1.3787</td><td bgcolor='#eeeeec' align='right'>15473776</td><td bgcolor='#eeeeec'><a href='http://www.php.net/mysql_real_escape_string' target='_new'>mysql_real_escape_string</a>
(  )</td><td title='C:\xampp\htdocs\Wordpress2\wp-includes\wp-db.php' bgcolor='#eeeeec'>..\wp-db.php<b>:</b>885</td></tr>
</table></font>
{"success":true,"return_data":{"redirect-to-thank-you-page":"http:\/\/localhost\/Wordpress2\/?page_id=5&e_reg_url_link=db2cfbfbb2b61d90deae9e18aa43d732"}}"