export const defaultNewPriceModifier = {
	id: 'NEW_PRICE',
	dbId: '',
	amount: null,
	desc: '',
	isBasePrice: false,
	isDeleted: false,
	isDefault: false,
	isDiscount: false,
	isPercent: false,
	isTax: false,
	name: '',
	order: 999,
	priceType: '',
	priceTypeOrder: 999,
	wpUser: 1,
};
