name: Deploy to demoee.org

on:
    push:
        branches: [dev]

jobs:
    deploy-to-barista-site:
        runs-on: ubuntu-latest
        name: Deploy to demoee.org
        steps:
            - name: Deploy via ssh
              uses: garygrossgarten/github-action-ssh@release
              with:
                  command: source ~/deploy-scripts/deploy-to-demoee.sh "event-espresso-core"
                  host: ${{ secrets.SERVER_EE_DEMO_SITES_HOST }}
                  username: ${{ secrets.SERVER_EE_DEVBOX_SITES_USERNAME }}
                  passphrase: ${{ secrets.SERVER_EE_DEVBOX_SITES_PASSPHRASE }}
                  privateKey: ${{ secrets.SERVER_EE_DEVBOX_SITES_PRIVATE_KEY }}
