name: PHP Lint & Test

on:
  pull_request:
    # Prevent this workflow from running on pull requests to barista branch
    branches-ignore:
      - 'barista'
    paths:
      - '**/*.php'

jobs:
  php-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '7.2' ]
    name: Lint with PHP ${{ matrix.php-version }}
    steps:
      - name: Checkout and set up LAMP
        uses: eventespresso/actions/packages/checkout-and-LAMP@main
        with:
          cache-key: ${{ runner.os }}-${{ secrets.GH_ACTIONS_CACHE_VERSION }}-lint
          php-tools: composer:v2
          php-version: ${{ matrix.php-version }}

      - name: PHP Lint
        run: composer config-eventespressocs --ansi && composer run-script lint:skip-warnings --ansi

  php-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
    name: Unit Tests with PHP ${{ matrix.php-version }}
    steps:

      - name: Set WP version for PHP 7
        if: ${{ startsWith( matrix.php-version, '7.' ) }}
        run: |
          echo "WP_VERSION=5.8.2" >> $GITHUB_ENV

      - name: Set WP version for PHP 8+
        if: ${{ startsWith( matrix.php-version, '8.' ) }}
        run: |
          echo "WP_VERSION=latest" >> $GITHUB_ENV

      - name: Set Composer version for PHP
        run: |
          echo "COMPOSER_VERSION=v2" >> $GITHUB_ENV

      - name: Set PHPUnit version for WP < 5.9
        if: ${{ env.WP_VERSION == '5.8.2' }}
        run: |
          echo "PHPUNIT_VERSION=v7" >> $GITHUB_ENV

      - name: Set PHPUnit version for WP >= 5.9
        if: ${{ env.WP_VERSION == 'latest' }}
        run: |
          echo "PHPUNIT_VERSION=v9" >> $GITHUB_ENV

      - name: Checkout and set up LAMP
        uses: eventespresso/actions/packages/checkout-and-LAMP@main
        with:
          cache-key: ${{ runner.os }}-${{ secrets.GH_ACTIONS_CACHE_VERSION }}-${{ env.WP_VERSION }}-test
          php-tools: composer:${{ env.COMPOSER_VERSION }}, phpunit:${{ env.PHPUNIT_VERSION }}, phpunit-polyfills
          php-version: ${{ matrix.php-version }}

      - name: Install WP Tests
        uses: eventespresso/actions/packages/install-wp-tests@main
        with:
          wp-version: ${{ env.WP_VERSION }}
          database: wordpress_test
          username: root
          password: root
          host: localhost

      - name: Run PHPUnit Tests
        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
        run: |
          phpunit --version
          phpunit --configuration tests/phpunit.xml
        # allow failure for PHP 8.1
        continue-on-error: ${{ matrix.php-version == 8.1 }}

        # run multisite test only with 1 PHP version
      - if: ${{ matrix.php-version == '7.4' }}
        name: Run PHPUnit Tests - WP Multisite
        env:
          WP_MULTISITE: 1
        run: phpunit --configuration tests/phpunit.xml
